# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-05 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20200706_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
